# Generated by Django 4.0.6 on 2022-08-02 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubcategorymodel',
            name='product',
        ),
        migrations.AddField(
            model_name='productsbrandmodel',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productsBrandModel_sub_category', to='product.productsproductmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsubcategorymodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productSubCategoryModel_category', to='product.produtscategorymodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtscategorymodel',
            name='product',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='produtsCategoryModel_product', to='product.productsproductmodel'),
            preserve_default=False,
        ),
    ]
