# Generated by Django 4.0.6 on 2022-08-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productsubcategorymodel_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsbrandmodel',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='productsubcategorymodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='produtscategorymodel',
            name='product',
        ),
    ]
