# Generated by Django 4.0.6 on 2022-08-03 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_productsbrandmodel_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtscategorymodel',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produtsCategoryModel_product', to='product.productsproductmodel'),
            preserve_default=False,
        ),
    ]
