# Generated by Django 4.0.6 on 2022-08-05 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0006_alter_productsbrandmodel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('upin', models.CharField(max_length=3)),
                ('payment_status', models.CharField(choices=[('IN PROGRESS', 'in progress'), ('SUCCESS', 'success')], default='IN PROGRESS', max_length=12)),
                ('total_amount', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentsModel_products', to='product.productsordermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentsModel_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
