# Generated by Django 4.0.6 on 2022-08-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_paymentsmodel_productpaymentsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscartmodel',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='productsCartModel_product', to='product.productsattributemodel'),
        ),
        migrations.AlterField(
            model_name='productscartmodel',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
