# Generated by Django 4.0.6 on 2022-08-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_productsattributemodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsattributemodel',
            name='price',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='productsattributemodel',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
