from django.urls import path
from . import views
urlpatterns = [
    path('product-detail-view/',views.productsLsitCreateView.as_view(),name='get_create_all_productsURL'),
    path('product-category-detail-view/',views.productsCategoryLsitCreateView.as_view(),name='get_create_all_product-CategoryURL'),
    path('product-model-detail-view/',views.productsBrandModelsLsitCreateView.as_view(),name='get_create_all_product_modelURL'),
    path('product-subcategory-detail-view/',views.productsSubCategoryLsitCreateView.as_view(),name='get_create_all_product_subcategoryURL'),
    path('product-attribute-detail-view/',views.productsAttributeModelLsitCreateView.as_view(),name='get_all_product_attributesURL'),
    path('product-cart-detail-view/',views.productsCartModelLsitCreateView.as_view(),name='get_create_all_user_cartURL'),
    path('product-order-detail-view/',views.productsOrderModelLsitCreateView.as_view(),name='get_create_all_ordersURL'),
    path('product-custom-attribute-detail-view/',views.productsAttributeModelCustomCreateView.as_view(),name='create_custom_product_attributeURL'),
    path('product-user-cart-detail-view/',views.productUserCartDetailView.as_view(),name='create_user_cart_detailsURL'),
    path('product-user-order-detail-view/', views.productsUsersOrderModelLsitView.as_view(), name='get_users_orders_URL'),
##_____________________________________crud_________________________________________________________________________________________________________________________________________________________
    path('product-get-view/<slug>/',views.prdocutsProductGetViews.as_view(),name='get_product_detailURL'),
    path('product-update-view/<slug>/',views.prdocutsProductUpdateViews.as_view(),name='update_productURL'),
    path('product-delete-view/<slug>/',views.prdocutsProductDeleteViews.as_view(),name='delete_productURL'),
    path('product-category-get-view/<slug>/',views.prdocutsCategoryGetViews.as_view(),name='get_category_detailURL'),
    path('product-category-update-view/<slug>/',views.prodcutsCategoryUpdateView.as_view(),name='update_categoryURL'),
    path('product-category-delete-view/<slug>/',views.productsCategoryDeleteView.as_view(),name='delete_categoryURL'),
    path('product-brand-get-view/<slug>/', views.prdocutsBrandGetViews.as_view(), name='get_brand_detailURL'),
    path('product-brand-update-view/<slug>/', views.prodcutsBrandUpdateView.as_view(), name='update_brandURL'),
    path('product-brand-delete-view/<slug>/', views.productsBrandDeleteView.as_view(), name='delete_brandURL'),
    path('product-subcategory-get-view/<slug>/', views.prdocutSubCategoryGetViews.as_view(), name='get_subcategory_detailURL'),
    path('product-subcategory-update-view/<slug>/', views.prodcutsSubCategoryUpdateView.as_view(), name='update_subcategoryURL'),
    path('product-subcategory-delete-view/<slug>/', views.productsSubCategoryDeleteView.as_view(), name='delete_subcategoryURL'),
    path('product-attribute-get-view/<slug>/', views.prdocutAttributeModelGetViews.as_view(), name='get_single_attribute_detailURL'),
    path('product-attribute-update-view/<slug>/', views.prodcutsAttributeModelUpdateView.as_view(), name='update_attributeURL'),
    path('product-attribute-delete-view/<slug>/', views.productsAttributeModelDeleteView.as_view(), name='delete_attributeURL'),
    path('product-cart-update-view/<slug>/', views.prodcutsCartUpdateView.as_view(), name='update__cart_detailURL'),
    path('product-cart-delete-view/<slug>/', views.productsCartDeleteView.as_view(), name='delete_cart_orderURL'),
    path('product-get-single-user-cart-view/<slug>/', views.prdocutsingleUserCartGetViews.as_view(), name='get_user-cart_orderURL'),
    path('product-order-update-view/<slug>/', views.prdocutOrderGetViews.as_view(), name='update__order_detailURL'),
    path('product-order-delete-view/<slug>/', views.productsorderDeleteView.as_view(), name='delete_s_orderURL'),
    path('product-get-single-user-order-view/<slug>/', views.prdocutsingleUserOrderGetViews.as_view(), name='get_user_ordersURL'),
    path('product-add-to-cart/<slug>/', views.productAddProductToCartView.as_view(), name='update__cart_detailURL'),
    # path('product-order-payment-view/<int:pk>/',views.productsPaymentOrderModelLsitView.as_view(),name='get_payment_ordersURL'),
    path('product-place-order/<slug>/', views.productsPlaceOrderModelLsitView.as_view(), name='place_order_detailURL'),
    path('product-list-all-order/', views.productsListOrderModelCreateView.as_view(), name='lis-all-orders_detailURL'),

]